name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone repo
      uses: actions/checkout@v2

    - name: Set version Node
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint
